#api:
#    resource: "@AdminBundle/Controller/"
#    type:     annotation

# Sonata-project
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#Liip imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"