<?php

namespace AdminBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Get galleries
     * @param type $limit
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGallery($limit = 0) 
    {
        return $this->findBy([], ['position' => 'ASC'], $limit);
    }
}
